Project 6: Simple Neural Network Forward Propagation

In [1]:
import numpy as np
from sklearn.datasets import load_iris

# Load dataset
iris = load_iris()

X = iris.data
y = iris.target

print("Input shape:", X.shape)
print("Target shape:", y.shape)
print("First 5 inputs:")
print(X[:5])
print("First 5 targets:")
print(y[:5])

Input shape: (150, 4)
Target shape: (150,)
First 5 inputs:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
First 5 targets:
[0 0 0 0 0]


In [2]:
# Set random seed
np.random.seed(42)

# Network size
input_size = 4
hidden_size = 5
output_size = 3

# Random weights
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros(hidden_size)

W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros(output_size)

print("W1 shape:", W1.shape)
print("W2 shape:", W2.shape)

W1 shape: (4, 5)
W2 shape: (5, 3)


In [3]:
def relu(x):
    return np.maximum(0, x)

In [4]:
# Take the first 5 Iris samples
X_sample = X[:5]

# First layer
Z1 = np.dot(X_sample, W1) + b1

# Apply activation function
A1 = relu(Z1)

# Output layer
Z2 = np.dot(A1, W2) + b2

print("Hidden layer output:")
print(A1)

print("\nFinal output:")
print(Z2)

Hidden layer output:
[[0.95252056 3.96750904 6.39082974 3.26409476 0.        ]
 [0.9702462  3.20555549 5.87757467 3.19422598 0.        ]
 [0.87041775 3.59562389 5.87732768 2.98705316 0.        ]
 [0.75147649 3.35838309 5.78420781 2.49904156 0.        ]
 [0.87943544 4.13925675 6.40280436 3.06484434 0.        ]]

Final output:
[[-12.56456076  -1.93790528   2.71184029]
 [-10.84185567  -1.67790137   2.80738385]
 [-11.48320306  -1.7431445    2.46031666]
 [-11.06999046  -1.32848574   1.57796757]
 [-12.87203771  -1.89051174   2.34969605]]


In [5]:
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

probabilities = softmax(Z2)

predictions = np.argmax(probabilities, axis=1)

print("Prediction probabilities:")
print(probabilities)

print("\nPredicted classes:")
print(predictions)

Prediction probabilities:
[[2.29831394e-07 9.47342862e-03 9.90526342e-01]
 [1.16772717e-06 1.11479798e-02 9.88850853e-01]
 [8.66889953e-07 1.47237236e-02 9.85275410e-01]
 [3.04750199e-06 5.18353154e-02 9.48161637e-01]
 [2.41587083e-07 1.42000489e-02 9.85799710e-01]]

Predicted classes:
[2 2 2 2 2]


In [6]:
print("Actual classes:   ", y[:5])
print("Predicted classes:", predictions)

Actual classes:    [0 0 0 0 0]
Predicted classes: [2 2 2 2 2]
